micronaut:
  application:
    name: greachconf-telegrambot
---
telegram:
  bots:
    greachconf:
      token: ${TELEGRAM_BOT_TOKEN}
      commands:
        - 'day'
        - 'help'
        - 'next'
        - 'talk'
        - 'start'
        - 'venue'
        - 'agenda'
        - 'speaker'
        - 'speakers'
