micronaut:
  application:
    name: greachconf-telegrambot
---
telegram:
  bots:
    greachconf:
      token: ${TELEGRAM_BOT_TOKEN}
      at-username: '@GreachConfBot'
---
telegram:
  bots:
    commands:
      about:
        parse-mode: 'Markdown'
        path: 'classpath:about.md'
      help:
        parse-mode: 'Markdown'
        path: 'classpath:help.md'

